/**
 * Regenerates public/sitemap.xml and public/robots.txt from the real content.
 *
 * Run it with `npm run sitemap` after adding a project or a research entry.
 * CI runs it before every build, so a forgotten run cannot ship a stale
 * sitemap — but running it locally keeps the committed file honest.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const publicDir = join(resolve(here, '..'), 'public')

const { site, orderedProjects, visibleResearch } = await import('../src/data/index.ts')

const origin = site.url.replace(/\/$/, '')
const today = new Date().toISOString().slice(0, 10)

/** Static pages first, then one entry per project and per research page. */
const routes = [
  { path: '', priority: '1.0' },
  { path: 'projects', priority: '0.9' },
  { path: 'research', priority: '0.8' },
  { path: 'engineering', priority: '0.7' },
  { path: 'about', priority: '0.7' },
  ...orderedProjects.map((p) => ({ path: `projects/${p.slug}`, priority: '0.8' })),
  // Research entries only get their own URL when they have a body to show.
  ...visibleResearch
    .filter((r) => r.body)
    .map((r) => ({ path: `research/${r.slug}`, priority: '0.6' })),
]

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.mjs. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
  .map(
    (r) => `  <url>
    <loc>${origin}/${r.path}</loc>
    <lastmod>${today}</lastmod>
    <priority>${r.priority}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`

const robots = `# Generated by scripts/build-sitemap.mjs. Do not edit by hand.
User-agent: *
Allow: /

Sitemap: ${origin}/sitemap.xml
`

writeFileSync(join(publicDir, 'sitemap.xml'), sitemap)
writeFileSync(join(publicDir, 'robots.txt'), robots)

console.log(`Wrote public/sitemap.xml (${routes.length} URLs) and public/robots.txt`)
